### ISSUE TITLE
Changing slide while clicked on one. 

### ISSUE THREAD

**Issue by mjarmoc** [jedrzejchalubek/Glide.js#101]
Hello, 

If I click on a slide, it goes one forward and brokes the order (chrome). Disabling touch distance (setting to false) solves it, however disables important thing :)

**Comment by jedrzejchalubek** [comment]
This few explanations is not helpful, please provide jsfiddle example.

**Comment by jedrzejchalubek** [comment]
2da8698 Should fixes this issue, please let me know.
