### ISSUE TITLE
Uncaught TypeError when using .destroy()

### ISSUE THREAD

**Issue by MalabarDesign** [jedrzejchalubek/Glide.js#103]
Hi!

Above all else, thx for this very good and lightweight plugin.

Here is my issue: when I use .destroy() on a slider, I have this console error (spawning again and again):

glide.js:776
Uncaught TypeError: Cannot read property 'eq' of undefined
Module.call @ glide.js:776
Module.make @ glide.js:1040
(anonymous function) @ glide.js:972

Mind, I aslo tested it on you basic.html example.

<script>
	var slider = $('#Glide').glide();//from your example
	var slider_api = slider.data('glide_api');//from your example
	$(document).on('click', '#kill', function(){slider_api.destroy();});//how I call destroy
</script>

I hope it's clear enough.
Maybe I do something wrong?
Thx for your help. :)

Cya and take care!

Thomas

**Comment by baptistebriel** [comment]
Hello,
I have a similar error when resizing the window;

```javascript
Uncaught TypeError: Cannot read property 'length' of undefined
Uncaught TypeError: Cannot read property 'eq' of undefined
```

Do you maybe have an idea? Thank you!

**Comment by zolotykh** [comment]
Hello,
I have a similar error when resizing the window;
I do destroy and reinit with new options.

**Comment by jedrzejchalubek** [comment]
Please, provide some sort of example (jsbin, jsfiddle). I can't reproduce this error, because of informations lack.
