### ISSUE TITLE
different time for sliders

### ISSUE THREAD

**Issue by joubertredrat** [jedrzejchalubek/Glide.js#106]
Hi guys,
I like your plugin and I use a lot in my projects, I liked a lot, then I have a question and a possible feature for this glide.
I have one project that I need to time between sliders need to be different, example, first I need 4000 ms before change to second slider, but second needs 7000 ms before change to third slider and so.

What you think? Is good idea? if isn't setted, assume default autoplay, if setted, use this on config.
Look a concept example here:
```html
    <div class="glide__wrapper">
        <ul class="glide__track">
            <li data-glide-autoplay="4000" class="glide__slide"></li>
            <li data-glide-autoplay="7000" class="glide__slide"></li>
            <li class="glide__slide"></li>
            <li data-glide-autoplay="3000" class="glide__slide"></li>
            <li class="glide__slide"></li>
            <li data-glide-autoplay="6000" class="glide__slide"></li>
            <li class="glide__slide"></li>
        </ul>
    </div>
```

If you like, I can to develop alpha here to we test and talk about.

Thanks again for this plugin

**Comment by jedrzejchalubek** [comment]
Yeah, It's a good idea.

**Comment by jedrzejchalubek** [comment]
Done in v2.0.5
