### ISSUE TITLE
IE9 Support

### ISSUE THREAD

**Issue by dejardine** [jedrzejchalubek/Glide.js#107]
Hi have you dropped IE9 support for the latest version?

**Comment by jedrzejchalubek** [comment]
Yeah. IE9 doesn't support css3 transitions, but support transforms. Slider should still work, but without animations.

**Comment by dejardine** [comment]
I'm not getting any sliding in IE9. If I revert to an older version (with revised markup) it works. Any ideas?

**Comment by jedrzejchalubek** [comment]
Plugin in `v1.0.*` supported fallback to older browsers, but `2.0.*` don't. 

Please tell which version you are using and paste here your markup.

**Comment by dejardine** [comment]
Here is a fiddle I created http://jsfiddle.net/Grafik/Ln59ec23/28/

**Comment by dejardine** [comment]
if I roll back to Glide Version: 1.0.65, and change the markup to the old format eg slides, slide etc — it works as expected in IE9

**Comment by jedrzejchalubek** [comment]
As I said above. IE9 is not supported, because it don't handle transform3d.

`v1.0.*` supported fallback to older browsers, but `2.0.*` don't. Thats all.

**Comment by dejardine** [comment]
All good, I'd expect the slides to at least change in IE9 — seems like it only needs a little bit of work as the callbacks work. I'll use an old version for this project.

**Comment by jedrzejchalubek** [comment]
Yeah, it's simple to add fallback. Need to add only checking method and refactor a little Transform module to switch between translate3d, translated (or even margin/position for IE8 support).

This was a conscious decision to not include it. Future proof.
