### ISSUE TITLE
Shifted slides

### ISSUE THREAD

**Issue by medhi** [jedrzejchalubek/Glide.js#109]
Hello, I have problem with shifted slides, if type is carousel or slider. I put your example here, where you can see it: https://jsfiddle.net/hrfp2un9/

Every slide is shifted couple of pixels to right.

Thanks!

**Comment by jedrzejchalubek** [comment]
Reset or normalize default css. Example: https://jsfiddle.net/hrfp2un9/3/

Next time please write on stackoverflow if you have implementation problems.
