### ISSUE TITLE
Help for install

### ISSUE THREAD

**Issue by BinoXXX** [jedrzejchalubek/Glide.js#113]
Hello i can't make the glide work can you help me? i placed the code like in the docs, copied the files in the root of my site, the glide slider appear and i see the next and prev buttons but if i place some image or colored square, like in your example, it does nothing. maybe i miss a file:

<script src="js/jquery.glide.js"></script> this is from the docs but where i can find the js folder or the jquery.glide.js??? in the zip there are none. i tried whit the glide.js file in "dist" folder but it doesn't work.

my site is: http://www.binoxproject.comule.com/
thanks!!!

**Comment by marcwieland95** [comment]
This is the place for issues and not support. Please ask for support on StackOverflow. Thanks

**Comment by BinoXXX** [comment]
Sorry i didn't know that. i was thinking this is the creator support page. I've made a post on StackOverflow now thanks!
