### ISSUE TITLE
Carousel is not working with wp

### ISSUE THREAD

**Issue by Behzadassadi** [jedrzejchalubek/Glide.js#114]
Hi.
Thanks for  Glide.js.

i use ur js + wp-query for my wp blog web..
only the slideshow is working for effect. and i cant get Carousel or slider..
and the other thing is :
when i add 
jQuery('#Glide').glide({
				type: 'slideshow'
			});
to my footer.. it will not always do the action for evey category i want to use this glide..
and i had to put it in another div and re run the action like this : 

jQuery             ('#slider1 #Glide').glide({
				type: 'slideshow'
			});    // slider1 for category-1
			jQuery('#slider2 #Glide').glide({
				type: 'slideshow'
                              // slider1 for category-2
			});
i don't know, maybe.. i am wrong !!!!!

Thanks

**Comment by jedrzejchalubek** [comment]
> The issue channel is especially for improvement proposals and bug reporting. If you have implementing problems, please write on StackOverflow with glidejs tag.
