### ISSUE TITLE
How to use refresh() method;

### ISSUE THREAD

**Issue by Hiagante** [jedrzejchalubek/Glide.js#115]
How do I refresh slider?

**Comment by jedrzejchalubek** [comment]
Chekout `examples/destroy.html` https://github.com/jedrzejchalubek/Glide.js/blob/master/examples/destroy.html

**Comment by Hiagante** [comment]
TypeError: b.Build.removeClones is not a function

**Comment by jedrzejchalubek** [comment]
Update to the lastest version.

**Comment by jhenderson** [comment]
Latest version gives "Uncaught TypeError: this.items[a].remove is not a function"

**Comment by Hiagante** [comment]
var slider = $('#Glide').glide({type:'slideshow'});
var slider_api = slider.data('glide_api');

$(document).ready(function() {
// code
// code
// code
slider_api.refresh();
});

Works fine, thanks.

**Comment by Moorst** [comment]
I'm having this issue with the latest version (2.0.3). Whenever I try to refresh on window resize, I get:

*glide.js:293 Uncaught TypeError: b.Build.removeClones is not a function*

Also, when I try to destory instead, I get this:

*glide.js:512 Uncaught TypeError: Cannot read property 'eq' of undefined*

Here's my code:

    $(document).ready(function() {

			var gallery = $('.gallery').glide({
				paddings: "20%",
				autoplay: false
			});
			var gallery_api = gallery.data('glide_api');

			var defaultSize = coreJs.breakpoint();

			var refreshGallery = coreJs.debounce(function() {
				var newSize = coreJs.breakpoint();

				console.log('default.'+defaultSize+' : '+'new.'+newSize);

				if(defaultSize != newSize){
					gallery_api.destroy();
					defaultSize = newSize;
				}
			}, 250);
			window.addEventListener('resize', refreshGallery);

    });

**Comment by jedrzejchalubek** [comment]
Make sure you're using the lastest version. Method `Build.removeClones` don't exist anywere, so it's imposible with lastest version.

If you getting glide via bower run `bower cache clean`. Maybe there is old version cached.
