### ISSUE TITLE
jump returns "move.substr is not a function"

### ISSUE THREAD

**Issue by caleb87** [jedrzejchalubek/Glide.js#120]
Attempting to jump with Glide 2.0.4 returns error "move.substr is not a function""
```javascript
var slider1 = $('#Slider1').glide();
slider1_api=slider1.data('glide_api');
slider1_api.jump(3, console.log('move to 3'));
```

This was added code to triggers_multiple_targets.html example.

**Comment by caleb87** [comment]
After reading the library code I figured out that it needs to be formatted like this:

    slider1_api('=3'); // jump to slide 3

The equals can also give a direction as ><

**Comment by jedrzejchalubek** [comment]
To be clear, via docs(http://glide.jedrzejchalubek.com/docs.html#api)

```
Direction param must be in special pattern:

> - move one forward
< - move one backward
={i} - go to {i} slide (eq. '=3', will go to third slide)
>> - rewinds to end (last slide)
<< - rewinds to start (first slide)
```
