### ISSUE TITLE
The example files are broken

### ISSUE THREAD

**Issue by gsmeira** [jedrzejchalubek/Glide.js#121]
All examples are broken due a bad jquery script call.

```
<script src="../bower_components/jquery/dist/jquery.js"></script>
```

No big deal, just in case you haven't noticed. The plugin is awesome, great work!

Gustavo

**Comment by jedrzejchalubek** [comment]
For working examples you need to fetch dependencies by running `bower install`.

Here's more info about bower: http://bower.io/

**Comment by Jany-M** [comment]
Where are the examples? Would be great if you could set up a page with different types of setups!
