### ISSUE TITLE
Touch don't work in Nexus devices on demo in docs page

### ISSUE THREAD

**Issue by mundgold** [jedrzejchalubek/Glide.js#122]
I use glidejs-plugin Version: 2.0.4. when i implement it likes described in the docs. The slider works - but on Android touch-devices (nexus 5, nexus 7 with chrome) i am not able to slide. On non-touch-devicses I can drag the the slides - but on the smartphone or tablet it is not possible. The swipeStart and swipeEnd Event fires on Touchdevices and on Non-Touch devices.

The swipe works on Apple iPad with chrome and safari.

Can anybody give me a hint, what I am doing wrong?

Thanks a lot!

```
var sliderTeaser = $('#sliderHome').glide({
     autoplay: 6000,
     swipeStart: function () {
             console.log('swipeStart');
           },
      swipeEnd: function () {
             console.log('swipeEnd');
            }
       });
```

**Comment by jedrzejchalubek** [comment]
Without debug log I can't say anything.

**Comment by mundgold** [comment]
Thanks for your reply. It seems that this doesn't work on your Example-Page (http://glide.jedrzejchalubek.com/docs.html)
I can slide with iPad but not with any Andriod-Based Touch-Device

**Comment by jedrzejchalubek** [comment]
I've make test and you're right. Will be fixed in next realase.

**Comment by jedrzejchalubek** [comment]
This was only wrong css stylings. Track element (where all swipe events are binded) had 0px height.
Adding height do the job.
