### ISSUE TITLE
Video question

### ISSUE THREAD

**Issue by medinlu** [jedrzejchalubek/Glide.js#124]
Is it possible to play and stop videos from youtube or vimeo in glide.js?

**Comment by jedrzejchalubek** [comment]
It's not job for glide itself. You need to search on stackoverflow how to stop video via youtube API and run that code in before/afterTransition callback.

```js
beforeTransition; function() {
    // code for pausing video
}
```

**Comment by medinlu** [comment]
Ok thanks! That's where I am into... ;-)
