### ISSUE TITLE
Uncaught TypeError: this.items[a].remove is not a function

### ISSUE THREAD

**Issue by schmooie** [jedrzejchalubek/Glide.js#129]
Calling destroy() on a Glide instance results in `Uncaught TypeError: this.items[a].remove is not a function`

**Comment by jedrzejchalubek** [comment]
There isn't any problems with `.destroy()` api method inside `examples/destroy.html`.

Could you tell more about where this issue appears?

**Comment by schmooie** [comment]
I'm using Glide.js in an Ember app where I've built out a component around the library. The issue that I'm running into is that Ember has extended JS object and array prototypes, so when you use a for-in loop to iterate over the items and call `.remove()` over each one of them, it's also doing it on other properties (including ones that don't have a `.remove` method. 

The gist of my error is in this StackOverflow thread: http://stackoverflow.com/questions/500504/why-is-using-for-in-with-array-iteration-such-a-bad-idea

    // Somewhere deep in your JavaScript library...
    Array.prototype.foo = 1;

    // Now you have no idea what the below code will do.
    var a = [1,2,3,4,5];
    for (var x in a){
        // Now foo is a part of EVERY array and 
        // will show up here as a value of 'x'.
    }

**Comment by jedrzejchalubek** [comment]
Good. Thanks.
