### ISSUE TITLE
slide content wrap issue

### ISSUE THREAD

**Issue by Maxhodges** [jedrzejchalubek/Glide.js#133]
content from a previous slide is visible on current slides (boxed in green here)

not why sure. trying to add margin or something to fix it, but still no luck

![image](https://cloud.githubusercontent.com/assets/957271/11298651/0028fe66-8fc4-11e5-8310-8c9189aaf9d4.png)

**Comment by Maxhodges** [comment]
seems the whole slide is offset to the right

**Comment by Maxhodges** [comment]
added styles to visualize the problem
![image](https://cloud.githubusercontent.com/assets/957271/11299486/8a74e08e-8fca-11e5-90e9-39fbf6cc4ef4.png)

**Comment by Maxhodges** [comment]
http://recordit.co/Td4qok9u2B

**Comment by jedrzejchalubek** [comment]
Without code can't say much, but it seems like css and implement problems (not slider). Make sure you reset styles (margins), especially if slider markup is `ul > li`.

**Comment by 50A** [comment]
I had the same problem. Adding `padding: 0;` to the ul fixed it. `<ul class="glide__track" style='padding:0;'>`
