### ISSUE TITLE
Demois broken

### ISSUE THREAD

**Issue by termoplus** [jedrzejchalubek/Glide.js#134]
hi,
When I download the files I cant open demo examples.

what should i do?

**Comment by jedrzejchalubek** [comment]
https://github.com/jedrzejchalubek/Glide.js/issues/121

No details, so i think same problem as above.

**Comment by termoplus** [comment]
sorry, what kind of details do you want?
when I download the ZIP i see no demo there? there are some example which are broken :(

please help me with this.
