### ISSUE TITLE
Resize issue: this.slides is undefined => Cannot read property 'length' of undefined / Cannot read property 'eq' of undefined

### ISSUE THREAD

**Issue by baptistebriel** [jedrzejchalubek/Glide.js#139]
Hello,
I have two Glide.js slider in one page; everything is working fine but for some reasons one of them breaks on resize. I have two errors in the console:

![screen shot 2016-01-08 at 10 20 59](https://cloud.githubusercontent.com/assets/2464663/12194604/905b060c-b5f1-11e5-8ddb-e31ff4308b3f.png)

```javascript
/**
 * Setup properties and values
 */
Glide.prototype.setup = function() {
	var modeMap = {
		horizontal: ['width', 'x'],
		vertical: ['height', 'y'],
	};

	this.size = modeMap[this.options.mode][0];
	this.axis = modeMap[this.options.mode][1];

	// sometimes, this.slides is undefined
	this.length = this.slides.length;

	this.paddings = this.getPaddings();
	this[this.size] = this.getSize();
};
```

```javascript
/**
 * Set active class
 * to current slide
 */
Module.prototype.active = function() {

	Glide.slides 
		.eq(Glide.current - 1).addClass(Glide.options.classes.active)
		.siblings().removeClass(Glide.options.classes.active);

};
```

Seems like the errors are being showed only if resized to a tablet / phone viewport width.
My guess is that `Glide.slides` are removed on resize somewhere.

If you have any ideas! Thanks.
Baptiste

**Comment by bfintal** [comment]
I'm seeing the cannot read property 'eq' error sometimes when destroying the slider.

**Comment by jedrzejchalubek** [comment]
I can't reproduce error. Could you prepare jsfinddle?

**Comment by bfintal** [comment]
You can see it when destroying it while animating. Unsure about resizing and other scenarios: http://codepen.io/bfintal/pen/PZyzpG

**Comment by baptistebriel** [comment]
Looks like the resize scenario happened because of something else on our side - but we sometimes have the error on destroy as well.
