### ISSUE TITLE
dragDistance doesn't seem to change anything?

### ISSUE THREAD

**Issue by stefang** [jedrzejchalubek/Glide.js#141]
Using the sliders in a small (200px), vertical config and I can seem to adjust the dragDistance to make them feel comfortable to use. Using your vertical example I added dragDistance: 50 to the setup and there was no change I could perceive. Cheers, Stefan

**Comment by jedrzejchalubek** [comment]
Distance limit option wasn't switching between mouse and touch events. Fixed in 6a10884.
