### ISSUE TITLE
Register as npm package

### ISSUE THREAD

**Issue by francoisromain** [jedrzejchalubek/Glide.js#143]
Is there a npm install glidejs?
thanks

**Comment by jedrzejchalubek** [comment]
You can install glide via bower.

**Comment by francoisromain** [comment]
who still uses bower nowadays : ). 
Btw, I like your plugin. thank you.

**Comment by Moorst** [comment]
I agree, bower has become obsolete - npm package would be ideal.

**Comment by francoisromain** [comment]
This work fine: 

npm install github:jedrzejchalubek/Glide.js

**Comment by deathmood** [comment]
I've published it under original name as it is in package.json. If author need this name on npm later -- I will give it to him. But now I cant wait while someone does this

**Comment by jedrzejchalubek** [comment]
Package published :)

https://www.npmjs.com/package/glidejs

**Comment by italomaia** [comment]
Please, document official package.

**Comment by aznnomness** [comment]
Is it possible to get the most recent version pushed to NPM?

What is the recommended way of pulling this package for builds?
