### ISSUE TITLE
interval reset with autoplay

### ISSUE THREAD

**Issue by dinko** [jedrzejchalubek/Glide.js#145]
When using the .go() method with autoplay, the autoplay interval does not get reset.

In my UX understanding, the reset is necessary. Otherwise you may sometimes have an issue that a slide immediately changes after you've manually advanced it because it was clicked near the end of an interval. There also may be other cases when a reset is necessary.

I'd suggest a .resetInterval() method or something like that.

**Comment by jedrzejchalubek** [comment]
It will be fixed. For now, just manually call `.pause()` before and `.play()` after.
