### ISSUE TITLE
Twice as tall as images

### ISSUE THREAD

**Issue by ricardozea** [jedrzejchalubek/Glide.js#151]
Hello,

Great plugin, but I'm having a problem.

When I include at least two images in the slide, the slider/carousel gets twice as tall as the images in it:

![screenshot - 4_15_2016 4_14_35 pm](https://cloud.githubusercontent.com/assets/1656481/14573848/93b6d552-0325-11e6-8f59-65d13d6ea17f.png)

The yellow box is the height of the carousel which is twice the height of the images in it. The red box is is the "ghost" image causing the problem.

Any image I put there, no matter the height, makes the height of the carousel double the height is supposed to be.

I already tried building everything from scratch 3 times considering that maybe I've missed something, edited the CSS, etc., but the results are always the same.

Any idea what's causing this problem?

Thanks.

**Comment by jedrzejchalubek** [comment]
Please add more details (show the code). Are you reseting or normalizing css? If no, I've recommending https://necolas.github.io/normalize.css/.

For quick debug you can try adding temporary fix and see if I'm right:

```
* {
    margin: 0;
    padding: 0;
    border: 0;
}
```

**Comment by ricardozea** [comment]
Your troubleshooting rule was very helpful. Seems the padding was somehow causing the issue, but TBH I have no idea what element is exactly the offender.

So I did a global selector and removed the padding from all elements (I know, not entirely ideal but oh well):

	.glide {
		position: relative;
		width: 100%;
		height: 100%;
		* { padding: 0; }
	}

And yes, I am using normalize.css.

Thanks for your fast reply :)
