### ISSUE TITLE
hoverpause doesn't work when hovering of prev/next buttons

### ISSUE THREAD

**Issue by ricardozea** [jedrzejchalubek/Glide.js#152]
This for me is a bug, so I decided to report it :)

I just noticed that `hoverpause: true ` doesn't work when hovering of `prev`/`next` buttons.

Not sure if that's intentional or not.

**Comment by jedrzejchalubek** [comment]
That is good hint. Will be in next release.

**Comment by jedrzejchalubek** [comment]
Fixed with 6526ca4

**Comment by ricardozea** [comment]
Awesome!

Can I just drop the updated file into my /js folder and it works? Or do I need to set something up first?

Thanks.

**Comment by jedrzejchalubek** [comment]
Only update glide js file.

**Comment by ricardozea** [comment]
Awesome! 

FWIW, here's one of the pages I'm using it right now: http://ricardozea.design/project-pearlmax.php

Thanks for adding this functionality so fast.
