### ISSUE TITLE
Alternating pause / play toggle button

### ISSUE THREAD

**Issue by greaveselliott** [jedrzejchalubek/Glide.js#24]
Hi,

I am attempting to create an alternating pause / play toggle button for my glide.js slider.

I am using the following mark-up for the button.

  < div class="slider-playback play">< div class="icon" >< /div >< /div >

and I am using the following jQuery / Javascript event for the toggle.

	jQuery('.slider-playback').on('click', function() {
		self = jQuery( this );		
		
		if ( self.hasClass('play') ) {
			self.removeClass( 'play' ).addClass( 'pause' );		// Toggle Pause / Play class
			glide.pause();

			console.log('Paused slideshow.');
			
		} else if (self.hasClass( 'pause' ) ) {
			self.removeClass( 'pause' ).addClass( 'play' );		// Toggle Pause / Play class
			glide.play();
			
			console.log('Resuming slideshow.');
		}
	});

**Comment by jedrzejchalubek** [comment]
Glide has been released version v2.0.0. If the problem remains, please set up a new thread.
