### ISSUE TITLE
Fade instead of Slide

### ISSUE THREAD

**Issue by scottcarlton** [jedrzejchalubek/Glide.js#32]
This slider is great! Simple with great selectors. I want to work on making it fade instead of slide....I know. It's called a slider, but for some reason a lot of people want it to fade. So want to see if I can get a fade transition instead. Someone who might be able to get this working faster than I could thought. Thanks.

**Comment by xxcram** [comment]
An option to fade was exactly what I needed.
I created a pull request, until now there's no merge into the glide.js repo.

However, for anyone who need fade transition - https://github.com/xxcram/Glide.js

**Comment by zackphilipps** [comment]
Awesome!! Thank you so much!

**Comment by xxcram** [comment]
My repo was merged into Glide.js. Slide and fade tranisition is now possible.

**Comment by zackphilipps** [comment]
:+1:

**Comment by jedrzejchalubek** [comment]
Glide has been released in version v2.0.0. If the problem remains, please set up a new thread.

**Comment by sonicpunk** [comment]
@jedrzejchalubek Can I ask why this feature was removed in v 3?
