### ISSUE TITLE
Setting empty string as navigationClass causes error

### ISSUE THREAD

**Issue by vgpena** [jedrzejchalubek/Glide.js#46]
If in the options, you declare `navigationClass: ''`, jQuery will throw the error "Uncaught Error: Syntax error, unrecognized expression: ."

It seems to be due to [this line](https://github.com/jedrzejchalubek/Glide.js/blob/master/src/jquery.glide.js#L755).

**Comment by jedrzejchalubek** [comment]
Glide has been released in version v2.0.0. If the problem remains, please set up a new thread.
