### ISSUE TITLE
Problem removing the slider (including callbacks).

### ISSUE THREAD

**Issue by chrism** [jedrzejchalubek/Glide.js#48]
Hi,

Firstly - fantastic work on this it seems like a really clean solution.

The slider if working great, but i've hit a problem when trying to remove the slider from the page.

Generally I find something like ```$(.slider').remove();``` works to get rid of all bound events - but no matter what I try it seems like the afterTransition event still fires.

Could you suggest a way I could remove it, or consider adding a .destroy() method  (suggested in a previous PR) which would include removing the callbacks?

Many thanks!

**Comment by jedrzejchalubek** [comment]
Glide has been released in version v2.0.0. If the problem remains, please set up a new thread.
