### ISSUE TITLE
slider-nav centering

### ISSUE THREAD

**Issue by fai222** [jedrzejchalubek/Glide.js#50]
To avoid inline styling and give simpler control to users I suggest removing 
left: 50% and margin-right inline styling from the nav, which the javascript sets, and instead use this for example on .slider-nav:

   left: 0;
   right: 0;
   margin-left: auto;
   margin-right: auto; 

Should center it just fine, and make it a bit simpler for users to control the nav with their own css, without fooling around in the javascript deleting and changing stuff :)

**Comment by jedrzejchalubek** [comment]
Glide has been released in version v2.0.0. If the problem remains, please set up a new thread.
