### ISSUE TITLE
Navigation html markup

### ISSUE THREAD

**Issue by proov** [jedrzejchalubek/Glide.js#52]
Hello,

I am cutomizing the slider to fit exactly my design. I'd like to put some tooltip on the navigation bullets, check this http://tympanus.net/codrops/2014/01/21/dot-navigation-styles/

Can we change the generated default markup ? i'd like to have **ul > li > a** instead of **a**

Maybe with a callback ? is it possible or u plan to do this in a future release ?

Many thanks

**Comment by jedrzejchalubek** [comment]
Glide has been released in version v2.0.0. If the problem remains, please set up a new thread.
