### ISSUE TITLE
API Method to Return Current Slide

### ISSUE THREAD

**Issue by danielwilber** [jedrzejchalubek/Glide.js#53]
There is an API method to return the number of the current slide, however I am looking for a way to return a jQuery object of the slide itself. I'd like to add a class of `.active` to the current slide.

This is more of a question than anything. Any help would be appreciated.

Best,
Daniel

**Comment by jedrzejchalubek** [comment]
Glide has been released in version v2.0.0. If the problem remains, please set up a new thread.
