### ISSUE TITLE
Can't get rid of a tab at the top

### ISSUE THREAD

**Issue by ghost** [jedrzejchalubek/Glide.js#61]
![capture](https://cloud.githubusercontent.com/assets/3706030/2813031/c0b487b2-ce79-11e3-8679-717ee5038997.PNG)

At the top of the page some tab (with gray, round dot at the right) was generated by glide.js. How to remove it without an affect on the workability?

![capture](https://cloud.githubusercontent.com/assets/3706030/2813043/1e693470-ce7a-11e3-9916-69c1974dabf2.PNG)

Open whole image to understand where the tab is.

**Comment by jedrzejchalubek** [comment]
Glide has been released in version v2.0.0. If the problem remains, please set up a new thread.
