### ISSUE TITLE
How to disable circular?

### ISSUE THREAD

**Issue by AccentureMalin** [jedrzejchalubek/Glide.js#73]
I know it says in the document to disable the circular option by
circular: false,

but when running the glide slider on my app, when I'm at the last item in the slide and slides to the left, it slides all the way back to the first item.

What I would like to have is that the slider does not slide back to the first one. I simply want the last slide-item to only be able to swipe back, not forward.

How to do this with glide.js ?

**Comment by jedrzejchalubek** [comment]
Glide has been released in version v2.0.0. If the problem remains, please set up a new thread.
