### ISSUE TITLE
Changing number of slides dynamically

### ISSUE THREAD

**Issue by maximulus** [jedrzejchalubek/Glide.js#77]
When I populate the slider dynamically (through jquery), and i change the number of slide items, it keeps the previous amount of slides. So if I initially create 3 slides, and then drop it down to two, it keeps 3 slides and makes the 3rd one blank. If I go from 2 to 3, it populates the third slide, but without the glide effect. I have tried to reinit after loading the sliders, but it does not work. Any ideas?

**Comment by jedrzejchalubek** [comment]
Glide has been released in version v2.0.0. If the problem remains, please set up a new thread.
