### ISSUE TITLE
glide.js add dynamically images to rotator

### ISSUE THREAD

**Issue by s3kawka** [jedrzejchalubek/Glide.js#78]
hello, i am not good in writing in english so i'll get to the point:
i have a problem with glide.js, i want to append a photos to list in glide.js rotator, so i used his option like "beforeInit" but this doesnt work, i mean rotator doesnt display images, his list (ul) width is set to 0, so images are not displayed in right position. when i want to reinit this glide i have communicat "undefined is not a function" but this glide is defined. I dont know how to fix this.

My code:

            var glide = $('#paintSlider').glide({
		autoplay : 0,
		hoverpause : false,
		touchDistance : false,
		navigation : false,

		arrowRightText : '',
		arrowLeftText : '',
		circular : true
                beforeInit : function() {
					var ile = $("span.holder3pic span").length;
					var tablica_img = new Array(ile);
					var indeks = 0;
		
					$("span.holder3pic span").each(function() {
						var img_src = $(this).find("img").attr("src");
		
						tablica_img[indeks] = img_src;
		
						indeks += 1;
					});
					for (var i = 0; i < ile; i++) {
		
						var img_el = '<li class="slide paint"><span ><img src="' + tablica_img[i] + '" alt=""/></span></li>';
						$("div#paintSlider ul").append(img_el);
					}
					
				}
		
		
	}).data('api_glide');

and this code append 'li" elements but ul still have width=0, so the images are not displayed, i tried after this code do " glide.reinit();" but like i said before i have an error,
How can i fix it?

**Comment by jedrzejchalubek** [comment]
BeforeInit callback runs when slider children are already stored.
Fill slider before runs $().glide().
