### ISSUE TITLE
Clicking arrows too fast makes page jump to top

### ISSUE THREAD

**Issue by rihok** [jedrzejchalubek/Glide.js#79]
Title says it all I think. Sometimes I want to quickly find a slide and click the arrow a few times too quickly and the page just jumps back to the top. I think there's a prevent default being ignored somewhere or something.

Any help would be appreciated.

**Comment by jedrzejchalubek** [comment]
Glide has been released in version v2.0.0. If the problem remains, please set up a new thread.
