### ISSUE TITLE
jump to slide without showing intermediate slides

### ISSUE THREAD

**Issue by sendradesignstudio** [jedrzejchalubek/Glide.js#85]
i would like to jump to a specific slide without showing the intermediate slides,
for example jump from slide #1 to slide #4 without showing/sliding slide #2 and #3 
is it already possible?

**Comment by jedrzejchalubek** [comment]
Unfortunately, no. It remains to edit source, playing inside with slide method and wrapper.trigger('clearTransition').

**Comment by jedrzejchalubek** [comment]
Glide has been released in version v2.0.0. If the problem remains, please set up a new thread.
