### ISSUE TITLE
glide.current() undefined when using afterInit event

### ISSUE THREAD

**Issue by kirpalmakanga** [jedrzejchalubek/Glide.js#86]
Hi, I want to get the index of the current slide, right after glide is initiated, but the console returns "Uncaught TypeError: Cannot read property 'current' of undefined".

Here's the code I used to do so:

glide = $('.slider').glide({
	        afterInit: function(){
                     var index = glide.current();
	        }
	    }).data('api_glide');

**Comment by jedrzejchalubek** [comment]
Here is a lot of little mistakes and misunderstandings. This can't work.

1. Returning of API take plece until data() is in chain. So variable glide is not an api instance until there.
2. You sholud access global scope variable inside callback.
2. After init current slide is always 1. There is no real sense of access to it here from api.
