### ISSUE TITLE
Slides not 100% Width

### ISSUE THREAD

**Issue by idesigns-studio** [jedrzejchalubek/Glide.js#89]
Hello! This topic has kind of been answered here (https://github.com/jedrzejchalubek/Glide.js/issues/71), but since i don't really know javascript, i didn't understand exactly how and where to put the .reinit() code. 

Here is where i am having the issue: http://helenaswax.com/2015/

As you can see, the slides are stacking to the left, but as soon as you change the browser window size, it adjusts perfectly. Could you help me with that?

Thanks in advance!

**Comment by jedrzejchalubek** [comment]
It looks like you managed it by yourself. For future, probably script run before necessary DOM was ready, so wrong width calculation was performed.

**Comment by idesigns-studio** [comment]
Hello, actually, i cheated, i used an iframe :(. I didn't get it to work directly on the page.

**Comment by dokicro** [comment]
Hi,

I had the same problem and my janky solution vas:

```
setTimeout(() => {
  new Glide('.glide').mount();
}, 1);
```

**Comment by phpMagpie** [comment]
I'm having this same problem where the slides are being created with a width which should be 100%, but is 30px out which throws the slides way out.  As soon as I resize the window the issue resolves itself.

Any pointers as to how I can get glide to load correctly in the first place or trigger a resize event so it sorts itself?

**Comment by MailboxArsonist** [comment]
I'm also having the same problem, is there an actual solution other than a timeout?

**Comment by andershagbard** [comment]
@MailboxArsonist, you can try this.

```js
document.addEventListener('DOMContentLoaded', () => {
  // Mount glide here
});
```

**Comment by MailboxArsonist** [comment]
@andershagbard, thanks for the reply. I'm using it in a React application, so it's getting mounted in the componentDidMount method, the DOM has already loaded so I'm a little confused as to why its not working, works fine with a settimeout so maybe I'll just use this solution!

**Comment by andershagbard** [comment]
I actually ran info this issue myself. Thought my previous eventListener would fix it, but it didn't.

This code seems to make it consistent. Initially on page load, it will show the slider with the incorrect fix, but it will fix it when readyState is complete.

```js
const api = new Glide(carousel, settings).mount();

if (document.readyState !== 'complete') {
  document.addEventListener('readystatechange', () => {
    if (document.readyState === 'complete') {
      api.update();
    }
  });
}
```

**Comment by fromaline** [comment]
My really quick and dirty fix. Works pretty well for me.

```javascript
new Glide('.glide').mount()
document.querySelector('body').style.width = '99vw'
document.querySelector('body').style.width = '100vw'
```

**Comment by Keither** [comment]
I'm also having the same problem, i use for my light box image
i use time out 1 not working, i fixed 500 working fine
setTimeout(() => {
        new Glide('#modalLightBox .glide', { type: 'carousel' }).mount();
    }, 500);
sorry my Englisht not good!

**Comment by Enigama** [comment]
@johannesmutter Thanks, your solution save my life))))

**Comment by ultrono** [comment]
> Hi,
> 
> I had the same problem and my janky solution vas:
> 
> ```
> setTimeout(() => {
>   new Glide('.glide').mount();
> }, 1);
> ```

It's now 2023 and I'm genuinely disappointed that worked 😄

**Comment by 3xau1o** [comment]
worked for ESM version

```js
   setTimeout(() => {
        new Glide('.glide').mount();
        window.dispatchEvent(new Event('resize'))
    }, 1);
```
