### ISSUE TITLE
Not working multiple sliders on the page

### ISSUE THREAD

**Issue by rafisbb** [jedrzejchalubek/Glide.js#91]
Hello. In begin excuse me, English is not my language, therefore I will write with grammatic mistakes.
I have two sliders in page.
First slider has 4 slides.
Second slider has 8 slides.
Every slider consist of main DIV with different classname, and consist of equal children of these DIV blocks.
And sliders starting with $('.header_slider').glide({...}); and $('.eat_slider').glide({...});
Both of sliders has setting "autoplay"
First slider has 4 slider and autoplayed normally.
But second slider, which consist 8 slider, autoplayed normally only first 4 sliders, and go to first slide after fourth slider.
How I solve this problem?

**Comment by xxcram** [comment]
That's indeed a bug (see #59). There's also a workaround.

**Comment by jedrzejchalubek** [comment]
Glide has been released in version v2.0.0. If the problem remains, please set up a new thread.
