### ISSUE TITLE
Issue with sizing when initialising on empty element

### ISSUE THREAD

**Issue by michaelsmedley** [jedrzejchalubek/Glide.js#92]
Hi there

Having a bit of a problem when initialising the plugin on a hidden element.  To put this into context, I have a link that I want to open a 'notification' panel that users can swipe through.

In the first screenshot, this is with markup generated with the element (#notifications) visible:
![screen shot 2015-04-21 at 13 12 58](https://cloud.githubusercontent.com/assets/2039847/7251978/396297e4-e828-11e4-9e13-533090ea7e42.png)

This is a screenshot taken when the page loads with this element hidden though
![screen shot 2015-04-21 at 13 15 51](https://cloud.githubusercontent.com/assets/2039847/7252008/93e07b50-e828-11e4-9f74-df0ae0cabf20.png)

As you can see, it is shrinking the elements down to less then half their size.  My CSS doesn't have a width on either .slider, the ul or li within it (the CSS applied is from the demo). I am using Angular which may delay populating the content in the list items, but I am not calling the plugin until my data has been binded to the view.

Any help appreciated!!

**Comment by jedrzejchalubek** [comment]
Glide has been released in version v2.0.0. If the problem remains, please set up a new thread.
