### ISSUE TITLE
Calculated height of .glide__slide when slide contains text

### ISSUE THREAD

**Issue by seankmchenry** [jedrzejchalubek/Glide.js#95]
I'm using the latest build to display a slider that contains text-only slides. The slider displayed fine when I had it set up in version (1.0.7), but now it doesn't seem to calculate the slide height correctly.

Where the slides differ in height, obviously, because they contain varying amounts of text, the slider height is set to 280px (the _.glide_ class height value), so the text is cut off. Here's what it looks like:

![capturfiles_10](https://cloud.githubusercontent.com/assets/1355119/7476598/9f9f20dc-f31c-11e4-87d8-168d47245ebf.png)

I imagine the `overflow: hidden` value is part of the issue, but is obviously required for clearing purposes.

**Comment by jedrzejchalubek** [comment]
There no issue here. Just change styles to fit your case. The height and overflow isnt requered.

**Comment by seankmchenry** [comment]
I'm not sure _either_ of those values can be safely removed. Certainly, the overflow value is still required - `overflow-x: hidden` at the very least? Otherwise, you see all slides at once. That being said, the slider also doesn't seem to calculate height correctly if you remove the height CSS value.

**Comment by jedrzejchalubek** [comment]
I looked deeper on this and you're right. Now height isn't calculated at all and this is a good thing, but for cases like yours, there need to be new option `autoHeight` or something (that force height calculation).

Goes to list for next release :) Thanks.

**Comment by seankmchenry** [comment]
Thanks for the quick response! This is the best slider I've used and it only got better with the latest major release!

**Comment by jedrzejchalubek** [comment]
Autoheight added in v2.0.2.
