### ISSUE TITLE
Pass richer parameters to the callbacks

### ISSUE THREAD

**Issue by dejardine** [jedrzejchalubek/Glide.js#96]
Hey great plugin, is there any way to get the direction the slider is moving, then store it in a variable?

**Comment by jedrzejchalubek** [comment]
I can't imagine how it would have to act and what problems had to solve.

But, all triggers have `data-glide-dir` attribute with direction value in special pattern (see in documentation). You can bind these elements for own click event and read that attribute.

**Comment by dejardine** [comment]
From memory I was looking to hook the slider into velocity.js and write some custom animations for the slide change.

**Comment by jedrzejchalubek** [comment]
This question directed me to some improvement. To the callbacks should be passed richer parameters. Among other things, the direction.

**Comment by jedrzejchalubek** [comment]
Done in v2.0.5

**Comment by dejardine** [comment]
Niiiceee!

**Comment by jedrzejchalubek** [comment]
To replenish the topic, here's example (For caruosel type. If type is slider, everything is a lot easer):
 
```js
var lastIndex = 1;

slider.on("beforeTransition.glide", function(event, data) {
	lastIndex = data.index;
});

slider.on("afterTransition.glide", function(event, data) {
	var dir;

	// If we on right edge(end) and next slide index is first
	// direction is next
	if (lastIndex === data.length && data.index === 1) dir = '>';
	// If we on left edge(start) and next slide index is last
	// direction is prev
	else if (lastIndex === 1 && data.index === data.length) dir = '<';
	// If last index is smaller that current index direction is next
	// otherwise direction is prev
	else dir = (lastIndex < data.index) ? '>': '<';
	
	// log out
	console.log(dir);
});
```
