### ISSUE TITLE
Using data-glide-trigger fails when used in multiple sliders

### ISSUE THREAD

**Issue by saimiri** [jedrzejchalubek/Glide.js#98]
I have multiple sliders on a page, each with a unique id. Each has a customized navigation that uses `data-glide-trigger` to target the correct slider. When one navigation link is clicked, it triggers the move event multiple times, apparently once for each link. The navigation still works if `data-glide-dir` is a number, but if it's an arrow ("<" or ">") the results are erratic. On some sliders it jumps between the first and last slide, on one it moves to the last one but immediately jumps back to the first one.

**Comment by jedrzejchalubek** [comment]
Custom triggers were tied several times, this meant calling code many times. Should be fixed in the lastest commit, let me know if everything is ok now :)

**Comment by saimiri** [comment]
Wow, that was fast. After your commit the triggers seem to work ok now. Thanks! :)
