### ISSUE TITLE
custom-trigger need to be highlighted with "active" class

### ISSUE THREAD

**Issue by Jonathlee** [jedrzejchalubek/Glide.js#99]
Reference : demo in > triggers.html 

Current custom-triggers did not highlight which was selected / active selection. Need a callback for custom-triggers

**Comment by jedrzejchalubek** [comment]
You need to be creative here. Use before/afterTransition callback and manually handle active class on particular triggers.

I'm not sure that slider can easy handle it for you out of the box. I need to test that out.

**Comment by jedrzejchalubek** [comment]
I can't come up with any clean solution for this (without linking with ugly attrs etc.). Maybe someone will have some other ideas.

**Comment by jedrzejchalubek** [comment]
I've done some test. It's better to doing via events/callbacks. Example:

```js

slider.on("afterTransition.glide", function(event, data) {
    $('.custom-trigger').eq(data.index).addClass('active').siblings().removeClass('active');
});
```
